<?php

declare(strict_types=1);
namespace fucodo\registry\ViewHelpers;

use fucodo\registry\Domain\Repository\RegistryEntryRepository;
use Neos\Flow\Security\Account;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
use Neos\Flow\Annotations as Flow;

class RegistryValueViewHelper extends AbstractViewHelper
{
    /**
     * @Flow\Inject
     * @var RegistryEntryRepository
     */
    protected RegistryEntryRepository $registryRepository;

    public function initializeArguments()
    {
        parent::initializeArguments(); // TODO: Change the autogenerated stub
        $this->registerArgument('account', Account::class, 'Account to be checked', false);
        $this->registerArgument('namespace', 'string', 'Contains the registry entry namespace', true);
        $this->registerArgument('name', 'string', 'Contains the registry entry name', true);
        $this->registerArgument('fallback', 'mixed', 'mixed fallback', false, null);
    }

    public function render()
    {
        if ($this->arguments['account'] instanceof Account) {
            return $this->registryRepository->getForAccount(
                $this->arguments['account']->getAccountIdentifier(),
                $this->arguments['namespace'],
                $this->arguments['name'],
                $this->arguments['fallback']
            )?->getValue();
        }

        return $this->registryRepository->getValue(
            $this->arguments['namespace'],
            $this->arguments['name'],
            $this->arguments['fallback']
        );
    }
}
